describe('User menambahkan kategori produk', () => {    
    beforeEach(()=>{
        cy.visit("https://kasirdemo.belajarqa.com")
        cy.get('#email')
            .type('jaya45@mail.com')
            .should('have.value','jaya45@mail.com')
        cy.get('#password')
            .type('12345')
            .should('have.value','12345')
        cy.get('.chakra-button').click()
    });
    it('User menginputkan nama tapi tidak menginputkan deskripsi',function(){
        cy.get('[href="/categories"] > .css-ewi1jp').click()
        cy.url().should('include','/categories')
        cy.get('.css-1piskbq').click()
        cy.url().should('include','/categories/create')
        cy.get('#nama')
            .type('barang elektronik')
            .should('have.value','barang elektronik')
        cy.wrap('#deskripsi')
            .should('not.be', undefined)
        cy.get('.chakra-button').click()
        cy.url().should('include','/categories')
        cy.get('.css-njbp03 > #toast-1-title').should('have.text','success')      
    });
    it('User menginputkan nama dan deskripsi pada kategori produk baru',function(){
        cy.get('[href="/categories"] > .css-ewi1jp').click()
        cy.url().should('include','/categories')
        cy.get('.css-1piskbq').click()
        cy.url().should('include','/categories/create')
        cy.get('#nama')
            .type('barang pecah belah')
            .should('have.value','barang pecah belah')
        cy.get('#deskripsi')
            .type('barang yang terbuat dari kaca/keramik yang mudah pecah')
            .should('have.value','barang yang terbuat dari kaca/keramik yang mudah pecah')
        cy.get('.chakra-button').click()
        cy.url().should('include','/categories')
        cy.get('.css-njbp03 > #toast-1-title').should('have.text','success')
    });
    it('User tidak menginputkan nama dan deskripsi',function(){
        cy.get('[href="/categories"] > .css-ewi1jp').click()
        cy.url().should('include','/categories')
        cy.get('.css-1piskbq').click()
        cy.url().should('include','/categories/create')
        cy.wrap('#nama')
            .should('not.be', undefined)
        cy.wrap('#deskripsi')
            .should('not.be', undefined)
        cy.get('.chakra-button').click()
        cy.url().should('include','/categories/create')
        cy.get('.chakra-alert').should('have.text','"name" is not allowed to be empty')
    });
})