describe('User mengubah data kategori', () => {
    beforeEach(()=>{
        cy.visit("https://kasirdemo.belajarqa.com")
        cy.get('#email')
            .type('jaya45@mail.com')
            .should('have.value','jaya45@mail.com')
        cy.get('#password')
            .type('12345')
            .should('have.value','12345')
        cy.get('.chakra-button').click()
    });
    it('User mengubah data kategori yang tersimpan', function(){
        cy.get('[href="/categories"] > .css-ewi1jp').click()
        cy.url().should('include','/categories')
        cy.get('.css-xl71ch').get('button[type="button"]').eq(2).click()
        cy.contains('ubah').click()
        cy.url().should('include','/edit')
        cy.get('#deskripsi')
            .type('barang yang membutuhkan sumber energi listrik')
            .should('have.value','barang yang membutuhkan sumber energi listrik')
        cy.get('.chakra-button').click()
        cy.url().should('include','/categories')
        cy.get('.css-njbp03 > #toast-1-title').should('have.text','success')
    })
    it('User meperbaharui data nama dan deskripsi dengan data kosong', function(){
        cy.get('[href="/categories"] > .css-ewi1jp').click()
        cy.url().should('include','/categories')
        cy.get('.css-xl71ch').get('button[type="button"]').eq(2).click()
        cy.contains('ubah').click()
        cy.url().should('include','/edit')
        cy.get('#nama').clear()
            .should('not.be', undefined)
        cy.get('#deskripsi').clear()
            .should('not.be', undefined)
        cy.get('.chakra-button').click()
        cy.url().should('include','/edit')
        cy.get('.chakra-alert').should('have.text','"name" is not allowed to be empty')
    })
})